FROM docker.io/eclipse-temurin:21-jre-ubi9-minimal

RUN microdnf install -y /usr/bin/scp /usr/bin/sshpass /usr/bin/sftp

ADD target/http-service-1.0-SNAPSHOT.jar /http-service-1.0-SNAPSHOT.jar

ENV JAVA_OPTS=""

ENTRYPOINT java ${JAVA_OPTS} -jar /http-service-1.0-SNAPSHOT.jar