version: '3'
services:
  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "agent-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      # Optional specify file configuration instead of using environment variable scheme
      # To use, call "export OTEL_CONFIG_FILE=/sdk-config.yaml" before calling docker compose up
      OTEL_CONFIG_FILE:
      WZH_URL: "https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-20240422.0-x86_64-dvd1.iso.manifest"
    ports:
      - "8080:8080"
    depends_on:
      - collector
  collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.98.0
    volumes:
      - ./collector-config.yaml:/collector-config.yaml:Z
    command: ["--config=/collector-config.yaml"]
    expose:
      - "4318"
    ports:
      - "4318:4318"
